### ISSUE TITLE
Erro de reprodução!

### ISSUE THREAD

**Issue by MrZpower** [itallolegal/crp-iframe-player#18]
A extensão está com problemas, ele não está reproduzindo 
![Screenshot_1](https://user-images.githubusercontent.com/34309288/95597774-70f36880-0a25-11eb-8cb0-3e66aafec021.png)

**Comment by zsrwhite** [comment]
so esse anime ?

**Comment by Djamess** [comment]
aconteceu aqui, só dei refresh na aba e deu certo

**Comment by MrZpower** [comment]
> so esse anime ?
agora ja voltou a funcionar, mas antes era em todos

**Comment by MrZpower** [comment]
> aconteceu aqui, só dei refresh na aba e deu certo

antes nao estava indo mesmo assim, mas agora ja voltou

**Comment by FaleiroDudu** [comment]
Se tu ir nas configurações do Crunchyroll tu consegue selecionar a língua padrão, depois que fiz isso nunca mais tive esse problema

**Comment by NyannRR** [comment]
> > aconteceu aqui, só dei refresh na aba e deu certo
> 
> antes nao estava indo mesmo assim, mas agora ja voltou

Como vc resolveu? tô com esse erro faz meses

**Comment by metalicogamer** [comment]
Pra mim nao importa quantas vezes eu de F5 na pagina nunca volta e funciona tenho q ficar retirando a extensão e colocando ela dnv pra ver se funciona e na maioria das vezes nao vai

**Comment by stopolax** [comment]
Então meus manos, a extensão tem seus limites. Caso o anime não esteja com aquela barra azul em cima do player dizendo que tem amostra grátis você não consegue assistir, já que quando não se tem você não é permitido de reproduzir logo a falha vem da extensão não cobrir a falta do Premium na sua conta, mas isso não é culpa da extensão, apenas uma limitação. A CR confere se sua conta tem o premium quando o anime não tem amostra grátis, assim vocês não conseguem nem reproduzir como não podem comentar já que essas perdições apenas são dadas para membros premium ou com contas logadas com pagamento confirmado. Espero ter ajudado vocês.

Konosuba é um anime dublado e vocês podem assistir já que tem amostra, entretanto Dragon Ball não tem amostra grátis. Confere as imagens abaixo.

![Screenshot_103](https://user-images.githubusercontent.com/74798873/99858411-e3e31980-2b63-11eb-9036-35ea39cdc1b4.png)
![Screenshot_104](https://user-images.githubusercontent.com/74798873/99858419-e6de0a00-2b63-11eb-8f2e-25b1a01ad556.png)


Konosuba
![Screenshot_105](https://user-images.githubusercontent.com/74798873/99858467-02491500-2b64-11eb-9867-21c19ed9098d.png)

![Screenshot_106](https://user-images.githubusercontent.com/74798873/99858484-0a08b980-2b64-11eb-96a5-cce7a67e58d8.png)


As vezes vocês não percebem pq assim que a extensão detecta a amostra, eles apagam a mensagem em azul, percebam isso apertanto F5 na pagina. Não é bug!

**Comment by MrZpower** [comment]
Obrigado, não sabia disso
